name: Main Build

on:
  pull_request:
  push:
    branches:
    - master
    paths:
    - '*'
    - '!/docs/*' # Don't run workflow when files are only in the /docs directory

jobs:
  windows:
    name: Ubuntu
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server
      mongo:
        image: mongo
        ports:
        - 27017:27017
      postgres:
        image: postgres
        ports:
        - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - 1433:1433
        env:
          SA_PASSWORD: sa
      # mysql:
      #   image: mysql
      #   ports:
      #   - 3306:3306
      #   env:
      #     MYSQL_ROOT_PASSWORD: root
      #     MYSQL_DATABASE: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build
      run: dotnet build Build.csproj -c Release /p:CI=true
    - name: Test
      run: dotnet test Build.csproj -c Release --no-build /p:CI=true
      env:
        EnableTestLogging: true
        RedisConnectionString: redis:6379
        MongoDbConnectionString: mongodb://mongo:27017/test
        MySQLConnectionString: server=localhost;uid=root;pwd=root;database=test;Allow User Variables=true
        PostgreSqlConnectionString: Server=postgres;Database=test;User Id=postgres;Password=postgres;
        SQLServerConnectionString: Data Source=sqlserver;Initial Catalog=tempdb;User Id=sa;Password=sa;
    - name: Pack
      run: dotnet pack Build.csproj --no-build -c Release /p:Packing=true /p:PackageOutputPath=%CD%\.nupkgs /p:CI=true
