name: Main Build

on:
  pull_request:
  push:
    branches:
    - master
    paths:
    - '*'
    - '!/docs/*' # Don't run workflow when files are only in the /docs directory

jobs:
  vm-job:
    name: Ubuntu
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
        - 6379/tcp
        options: --entrypoint redis-server
      mongo:
        image: mongo
        ports:
        - 27017/tcp
      postgres:
        image: postgres
        ports:
        - 5432/tcp
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - 1433/tcp
        env:
          SA_PASSWORD: sa
      # mysql:
      #   image: mysql
      #   ports:
      #   - 3306:3306
      #   env:
      #     MYSQL_ROOT_PASSWORD: root
      #     MYSQL_DATABASE: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: .NET Build
      run: dotnet build Build.csproj -c Release /p:CI=true
    - name: .NET Test
      run: dotnet test Build.csproj -c Release --no-build /p:CI=true
      env:
        EnableTestLogging: true
        RedisConnectionString: localhost:${{ job.services.redis.ports[6379] }}
        MongoDbConnectionString: mongodb://localhost:${{ job.services.mongo.ports[27017] }}/test
        MySQLConnectionString: server=localhost;uid=root;pwd=root;database=test;Allow User Variables=true
        PostgreSqlConnectionString: Server=localhost:${{ job.services.postgres.ports[5432] }};Database=test;User Id=postgres;Password=postgres;
        SQLServerConnectionString: Data Source=tcp://localhost:${{ job.services.sqlserver.ports[1433] }};Initial Catalog=tempdb;User Id=sa;Password=sa;
    - name: .NET Lib Pack
      run: dotnet pack Build.csproj --no-build -c Release /p:Packing=true /p:PackageOutputPath=%CD%\.nupkgs /p:CI=true
